# Generated by Django 2.1.7 on 2019-02-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_winecollection_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='winecollection',
            name='s_no',
            field=models.IntegerField(default=None),
        ),
    ]
