# Generated by Django 2.1.7 on 2019-02-17 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_winecollection_s_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winecollection',
            name='s_no',
        ),
    ]
