# Generated by Django 2.1.7 on 2019-02-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_winecollection_s_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winecollection',
            name='price',
            field=models.FloatField(default=None),
        ),
    ]
