# Generated by Django 2.1.7 on 2019-02-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190217_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winecollection',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='winecollection',
            name='description',
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='winecollection',
            name='designation',
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='winecollection',
            name='points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='winecollection',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='winecollection',
            name='province',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='winecollection',
            name='region_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='winecollection',
            name='region_2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='winecollection',
            name='variety',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='winecollection',
            name='winery',
            field=models.CharField(max_length=100),
        ),
    ]
